import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { AppContextProvider } from '@/context/AppContext'
import { TQueryProvider } from '@/provider/TQueryProvider'
const montserrat = Montserrat({ subsets: ['latin'] })
import { updateApiClient } from 'geo-survey-map-shared-modules'
import { MarkerFormContextProvider } from '@/context/AddMarkerFormContext'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`overflow-hidden ${montserrat.className}`}>
				<TQueryProvider>
					<AppContextProvider>
						<MarkerFormContextProvider>{children}</MarkerFormContextProvider>
					</AppContextProvider>
				</TQueryProvider>
			</body>
		</html>
	)
}
